"""empty message

Revision ID: 97410b70da0b
Revises: 01803d9f8d2b
Create Date: 2019-10-02 09:38:25.613859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97410b70da0b'
down_revision = '01803d9f8d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('comment', sa.TEXT(), nullable=True))
    op.add_column('books', sa.Column('format', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('series', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('sold', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'sold')
    op.drop_column('books', 'series')
    op.drop_column('books', 'format')
    op.drop_column('books', 'comment')
    # ### end Alembic commands ###
