"""add placement column

Revision ID: ff18b6febd17
Revises: 97410b70da0b
Create Date: 2019-10-02 10:21:45.718836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff18b6febd17'
down_revision = '97410b70da0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('placement', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'placement')
    # ### end Alembic commands ###
